export const EVENT_CATEGORY_OPTIONS: Record<string, string[]> = {
  "Health Science": [
    "Behavioral Health",
    "Biomedical Equipment Technician",
    "Dental Terminology",
    "Health Informatics",
    "Healthcare Administration",
    "Human Growth & Development",
    "Medical Law & Ethics",
    "Medical Math",
    "Medical Reading",
    "Nutrition",
    "Pathophysiology",
    "Pharmacology",
    "World Health & Disparities",
  ],
  "Health Professions": [
    "Biotechnology",
    "Clinical Laboratory Science",
    "Clinical Nursing",
    "Clinical Specialty",
    "Dental Science",
    "Family Medicine Physician",
    "Home Health Aide",
    "Medical Assisting",
    "Nursing Assisting",
    "Occupational Therapy",
    "Patient Care Technician",
    "Pharmacy Science",
    "Phlebotomy",
    "Physical Therapy",
    "Sports Medicine",
    "Surgical Technologist",
    "Veterinary Science",
  ],
  ATC: [
    "Allied Health Statistics",
    "Anatomy & Physiology",
    "Biochemistry",
    "Biology",
    "Career Development",
    "Environmental Health",
    "General Chemistry",
    "Human Heredity",
    "Math For Health Professionals",
    "Microbiology",
    "Organic Chemistry",
    "Physics College",
    "AAFP Family Medicine Career Test",
    "Leadership",
  ],
  "Emergency Preparedness": [
    "CERT Skills",
    "CPR/First Aid",
    "Emergency Medical Technician",
    "Epidemiology",
  ],
  Teamwork: [
    "Biomedical Debate",
    "Creative Problem Solving",
    "Forensic Science",
    "HOSA Bowl",
    "Parliamentary Procedure",
  ],
  Recognition: [
    "Healthcare Issues",
    "HOSA History",
  ],
};

export const ALL_REQUESTABLE_EVENTS = Object.values(EVENT_CATEGORY_OPTIONS).flat();
